CREATE INDEX MH_DATA_DATA_TYPE_IDX
    ON mh_variable (DATA_TYPE);

CREATE INDEX MH_DATA_REF_ID_REF_TYPE_IDX
    ON mh_variable (REF_ID, REF_TYPE);

CREATE INDEX MH_TASK_WORKBOOK_ID_IDX
    ON MH_TASK (WORKBOOK_ID);