CREATE INDEX MH_BATCH_COMPANY_ID_IDX
    ON MH_BATCH (COMPANY_ID);

CREATE INDEX MH_SOURCE_CODE_COMPANY_ID_IDX
    ON MH_SOURCE_CODE (COMPANY_ID);

CREATE INDEX MH_EXEC_CONTEXT_ID_SOURCE_CODE_ID_IDX
    ON MH_EXEC_CONTEXT (ID, SOURCE_CODE_ID);
