CREATE TABLE MH_ATLAS_TASK
(
    ID          SERIAL PRIMARY KEY,
    VERSION     NUMERIC(5, 0)  NOT NULL,
    ATLAS_ID    NUMERIC(10, 0)   NOT NULL,
    TASK_ID     NUMERIC(10, 0)   NOT NULL,
    PARAMS      TEXT not null
);

CREATE INDEX MH_ATLAS_TASK_ATLAS_ID_IDX
    ON MH_ATLAS_TASK (ATLAS_ID);

CREATE INDEX MH_ATLAS_TASK_ATLAS_ID_TASK_ID_IDX
    ON MH_ATLAS_TASK (ATLAS_ID, TASK_ID);
