-- Create META_STORAGE_STUB table for PostgreSQL
-- Stub table. It exists so the module carries a real Liquibase-managed schema on the MAIN
-- datasource, alongside the SQLite file the meta storage itself lives in. The two are separate
-- stores on purpose; see MetaStorageConfig for why only one of them is a Spring DataSource bean.
-- BIGINT GENERATED BY DEFAULT AS IDENTITY rather than SERIAL - int4 SERIAL PKs on high-churn
-- tables are the pattern the Aurora audit flagged.

CREATE TABLE META_STORAGE_STUB (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSION INT DEFAULT 0 NOT NULL,
    COMPANY_ID BIGINT NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    PARAMS TEXT NOT NULL,
    CREATED_ON BIGINT NOT NULL,
    CONSTRAINT UK_META_STORAGE_STUB_CODE UNIQUE (COMPANY_ID, CODE)
);

CREATE INDEX IDX_META_STORAGE_STUB_COMPANY ON META_STORAGE_STUB(COMPANY_ID);
