-- Right now this functionality isn't used
-- ============

CREATE TABLE AIAI_S_METADATA (
  ID          INT(10) NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  VERSION     NUMERIC(5, 0)  NOT NULL,
  META_KEY    VARCHAR(50),
  META_VALUE  VARCHAR(250)
);

CREATE UNIQUE INDEX AIAI_S_METADATA_UNQ_IDX
  ON AIAI_S_METADATA (META_KEY);

CREATE TABLE AIAI_S_EXPERIMENT_SEQUENCE (
  ID          INT(10) NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  EXPERIMENT_SEQUENCE_ID          NUMERIC(10, 0) NOT NULL,
  VERSION      NUMERIC(5, 0)  NOT NULL,
  CREATED_ON   bigint not null,
  LAUNCHED_ON  bigint,
  FINISHED_ON  bigint,
  REPORTED_ON  bigint,
  PARAMS       MEDIUMTEXT not null,
  METRICS      MEDIUMTEXT,
  IS_REPORTED  tinyint(1) not null default 0,
  IS_DELIVERED  tinyint(1) not null default 0,
  SNIPPET_EXEC_RESULTS  MEDIUMTEXT
);

CREATE UNIQUE INDEX AIAI_S_EXPERIMENT_SEQUENCE_UNQ_IDX
  ON AIAI_S_EXPERIMENT_SEQUENCE (EXPERIMENT_SEQUENCE_ID);
